# Generated by Django 6.0.7 on 2026-08-20 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "netbox_dhcp",
            "0003_optiondefinition_option_definition_standard_or_unique_parent_object_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="subnet",
            name="subnet_id",
            field=models.PositiveBigIntegerField(
                blank=True,
                validators=[django.core.validators.MaxValueValidator(4294967295)],
            ),
        ),
    ]
