# Generated by Django 6.1 on 2026-09-01 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_dhcp", "0004_alter_subnet_subnet_id"),
        ("users", "0016_default_ordering_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientclass",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="dhcpcluster",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="dhcpserver",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="hostreservation",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="optiondefinition",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="pdpool",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="pool",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
    ]
